### ISSUE TITLE
Falsche Geonames URIs

### ISSUE THREAD

**Issue by alexander-winkler** [deutsche-nationalbibliothek/lds-vocabulary#2]
Die kanonische Form des Geonames URIs lautet `https://sws.geonames.org/<ID>/`, nicht `http://www.geonames.org/<ID>` (vgl. <http://www.geonames.org/ontology/documentation.html>)

**Comment by acka47** [comment]
As #4 is merged and this is fixed, we can close this issue, @thoffma . (I don't have the rights to do so.)

**Comment by thoffma** [comment]
Yes, it is merged into the develop branch.
